version: "3"
services:
  db:
    image: "postgres:12-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "gxkai"
      POSTGRES_PASSWORD: "gxkai"
      POSTGRES_DB: "database_chat"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres'" ]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: "on-failure"